In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("fifa.csv")

In [30]:
argentina_matches = df[(df["Team_1"] == "Argentina") |
                         (df["Team_2"] == "Argentina")]
argentina_matches

,Match_ID,Date,Venue,City,Stadium,Stage,Team_1,Team_2,Team_1_FIFA_Rank,Team_2_FIFA_Rank,...,Team_1_Red_Cards,Team_2_Red_Cards,Team_1_xG,Team_2_xG,Attendance,Referee,Weather,Team_1_Goals,Team_2_Goals,Winner
17,M018,2026-06-28,"Lumen Field, Seattle",Seattle,Lumen Field,Group Stage,Argentina,Ecuador,1,25,...,0,0,1.56,2.21,75533,Referee_4,Rainy,0,2,Ecuador

In [31]:
df.head()

,Match_ID,Date,Venue,City,Stadium,Stage,Team_1,Team_2,Team_1_FIFA_Rank,Team_2_FIFA_Rank,...,Team_1_Red_Cards,Team_2_Red_Cards,Team_1_xG,Team_2_xG,Attendance,Referee,Weather,Team_1_Goals,Team_2_Goals,Winner
0,M001,2026-06-11,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Group Stage,Qatar,Italy,41,8,...,0,0,1.24,1.14,67651,Referee_3,Sunny,3,2,Qatar
1,M002,2026-06-12,"MetLife Stadium, New York",New York,MetLife Stadium,Group Stage,Portugal,USA,6,14,...,0,0,1.57,0.10,50463,Referee_28,Rainy,0,0,Draw
2,M003,2026-06-13,"Mercedes-Benz Stadium, Atlanta",Atlanta,Mercedes-Benz Stadium,Group Stage,Morocco,Belgium,18,10,...,0,0,2.43,1.14,70108,Referee_35,Sunny,2,0,Morocco
3,M004,2026-06-14,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Group Stage,Ecuador,Portugal,25,6,...,0,0,0.98,1.10,45229,Referee_15,Sunny,0,3,Portugal
4,M005,2026-06-15,"Mercedes-Benz Stadium, Atlanta",Atlanta,Mercedes-Benz Stadium,Group Stage,Ecuador,Morocco,25,18,...,0,0,1.55,0.10,44679,Referee_39,Cloudy,0,0,Draw

In [13]:
df.shape

(104, 32)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Match_ID                104 non-null    object
 1   Date                    104 non-null    object
 2   Venue                   104 non-null    object
 3   City                    104 non-null    object
 4   Stadium                 104 non-null    object
 5   Stage                   104 non-null    object
 6   Team_1                  104 non-null    object
 7   Team_2                  104 non-null    object
 8   Team_1_FIFA_Rank        104 non-null    int64
 9   Team_2_FIFA_Rank        104 non-null    int64
 10  Team_1_Possession       104 non-null    int64
 11  Team_2_Possession       104 non-null    int64
 12  Team_1_Shots            104 non-null    int64
 13  Team_2_Shots            104 non-null    int64
 14  Team_1_Shots_On_Target  104 non-null    int64
 15  Team_2_Shots_On_Target  104 non-null    int64
 16  Team_1_Corners          104 non-null    int64
 17  Team_2_Corners          104 non-null    int64
 18  Team_1_Fouls            104 non-null    int64
 19  Team_2_Fouls            104 non-null    int64
 20  Team_1_Yellow_Cards     104 non-null    int64
 21  Team_2_Yellow_Cards     104 non-null    int64
 22  Team_1_Red_Cards        104 non-null    int64
 23  Team_2_Red_Cards        104 non-null    int64
 24  Team_1_xG               104 non-null    float64
 25  Team_2_xG               104 non-null    float64
 26  Attendance              104 non-null    int64
 27  Referee                 104 non-null    object
 28  Weather                 104 non-null    object
 29  Team_1_Goals            104 non-null    int64
 30  Team_2_Goals            104 non-null    int64
 31  Winner                  104 non-null    object
dtypes: float64(2), int64(19), object(11)
memory usage: 26.1+ KB

In [20]:
df.isna().sum()

Match_ID                  0
Date                      0
Venue                     0
City                      0
Stadium                   0
Stage                     0
Team_1                    0
Team_2                    0
Team_1_FIFA_Rank          0
Team_2_FIFA_Rank          0
Team_1_Possession         0
Team_2_Possession         0
Team_1_Shots              0
Team_2_Shots              0
Team_1_Shots_On_Target    0
Team_2_Shots_On_Target    0
Team_1_Corners            0
Team_2_Corners            0
Team_1_Fouls              0
Team_2_Fouls              0
Team_1_Yellow_Cards       0
Team_2_Yellow_Cards       0
Team_1_Red_Cards          0
Team_2_Red_Cards          0
Team_1_xG                 0
Team_2_xG                 0
Attendance                0
Referee                   0
Weather                   0
Team_1_Goals              0
Team_2_Goals              0
Winner                    0
dtype: int64

In [21]:
df.describe()

,Team_1_FIFA_Rank,Team_2_FIFA_Rank,Team_1_Possession,Team_2_Possession,Team_1_Shots,Team_2_Shots,Team_1_Shots_On_Target,Team_2_Shots_On_Target,Team_1_Corners,Team_2_Corners,...,Team_2_Fouls,Team_1_Yellow_Cards,Team_2_Yellow_Cards,Team_1_Red_Cards,Team_2_Red_Cards,Team_1_xG,Team_2_xG,Attendance,Team_1_Goals,Team_2_Goals
count,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,...,104.000000,104.000000,104.000000,104.0,104.0,104.000000,104.000000,104.000000,104.000000,104.000000
mean,24.144231,24.778846,48.548077,51.451923,11.346154,11.163462,4.240385,4.115385,5.096154,5.567308,...,13.384615,2.807692,2.750000,0.0,0.0,1.369904,1.196250,62742.875000,1.413462,1.153846
std,13.766724,13.550307,8.736576,8.736576,3.290968,3.821530,2.002402,2.328830,2.901353,2.564751,...,4.520305,1.689930,1.744617,0.0,0.0,0.679066,0.665925,12618.015239,1.075866,0.983053
min,1.000000,2.000000,35.000000,35.000000,2.000000,3.000000,0.000000,0.000000,1.000000,1.000000,...,5.000000,0.000000,0.000000,0.0,0.0,0.100000,0.100000,40363.000000,0.000000,0.000000
25%,14.750000,13.750000,40.000000,46.000000,9.000000,8.000000,3.000000,2.750000,2.000000,3.750000,...,9.750000,2.000000,1.000000,0.0,0.0,0.870000,0.715000,50478.750000,1.000000,0.000000
50%,24.500000,23.000000,49.500000,50.500000,12.000000,11.000000,4.000000,4.000000,5.000000,6.000000,...,13.000000,3.000000,3.000000,0.0,0.0,1.375000,1.105000,62970.500000,1.000000,1.000000
75%,36.250000,38.000000,54.000000,60.000000,13.000000,13.000000,6.000000,6.000000,8.000000,8.000000,...,18.000000,4.000000,4.000000,0.0,0.0,1.785000,1.635000,73778.250000,2.000000,2.000000
max,48.000000,48.000000,65.000000,65.000000,19.000000,26.000000,9.000000,12.000000,10.000000,10.000000,...,20.000000,5.000000,5.000000,0.0,0.0,3.020000,2.830000,84944.000000,4.000000,4.000000

In [26]:
df.head(0)

Empty DataFrame
Columns: [Match_ID, Date, Venue, City, Stadium, Stage, Team_1, Team_2, Team_1_FIFA_Rank, Team_2_FIFA_Rank, Team_1_Possession, Team_2_Possession, Team_1_Shots, Team_2_Shots, Team_1_Shots_On_Target, Team_2_Shots_On_Target, Team_1_Corners, Team_2_Corners, Team_1_Fouls, Team_2_Fouls, Team_1_Yellow_Cards, Team_2_Yellow_Cards, Team_1_Red_Cards, Team_2_Red_Cards, Team_1_xG, Team_2_xG, Attendance, Referee, Weather, Team_1_Goals, Team_2_Goals, Winner]
Index: []

[0 rows x 32 columns]

In [25]:
df2 = df[["Team_1","Team_2","Team_1_Goals",
          "Team_2_Goals","Winner"]]
df2.head()

     Team_1    Team_2  Team_1_Goals  Team_2_Goals    Winner
0     Qatar     Italy             3             2     Qatar
1  Portugal       USA             0             0      Draw
2   Morocco   Belgium             2             0   Morocco
3   Ecuador  Portugal             0             3  Portugal
4   Ecuador   Morocco             0             0      Draw

In [35]:
df[df["Stage"]=="Final"]

,Match_ID,Date,Venue,City,Stadium,Stage,Team_1,Team_2,Team_1_FIFA_Rank,Team_2_FIFA_Rank,...,Team_1_Red_Cards,Team_2_Red_Cards,Team_1_xG,Team_2_xG,Attendance,Referee,Weather,Team_1_Goals,Team_2_Goals,Winner
103,M104,2026-09-22,"Mercedes-Benz Stadium, Atlanta",Atlanta,Mercedes-Benz Stadium,Final,Cameroon,Iran,34,40,...,0,0,1.11,1.1,82421,Referee_22,Sunny,1,0,Cameroon

In [36]:
df[(df["Team_1_Goals"])+(df["Team_2_Goals"]) >4]

,Match_ID,Date,Venue,City,Stadium,Stage,Team_1,Team_2,Team_1_FIFA_Rank,Team_2_FIFA_Rank,...,Team_1_Red_Cards,Team_2_Red_Cards,Team_1_xG,Team_2_xG,Attendance,Referee,Weather,Team_1_Goals,Team_2_Goals,Winner
0,M001,2026-06-11,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Group Stage,Qatar,Italy,41,8,...,0,0,1.24,1.14,67651,Referee_3,Sunny,3,2,Qatar
20,M021,2026-07-01,"AT&T Stadium, Dallas",Dallas,AT&T Stadium,Group Stage,Norway,Australia,30,21,...,0,0,2.07,1.59,62872,Referee_5,Cloudy,3,3,Draw
46,M047,2026-07-27,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Group Stage,Turkey,Tunisia,28,47,...,0,0,2.42,1.97,83790,Referee_25,Rainy,4,1,Turkey
52,M053,2026-08-02,"MetLife Stadium, New York",New York,MetLife Stadium,Group Stage,Qatar,Egypt,41,32,...,0,0,2.84,2.53,71308,Referee_8,Sunny,3,3,Draw
59,M060,2026-08-09,"MetLife Stadium, New York",New York,MetLife Stadium,Group Stage,Panama,Morocco,44,18,...,0,0,1.80,1.52,45979,Referee_31,Rainy,4,2,Panama
72,M073,2026-08-22,"AT&T Stadium, Dallas",Dallas,AT&T Stadium,Round of 32,Panama,Costa Rica,44,35,...,0,0,1.64,1.01,65211,Referee_31,Sunny,2,3,Costa Rica
76,M077,2026-08-26,"Lumen Field, Seattle",Seattle,Lumen Field,Round of 32,Croatia,South Korea,11,17,...,0,0,1.60,0.51,84323,Referee_26,Rainy,4,1,Croatia
77,M078,2026-08-27,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Round of 32,Portugal,Poland,6,26,...,0,0,0.85,1.63,81847,Referee_24,Sunny,2,3,Poland
84,M085,2026-09-03,"Hard Rock Stadium, Miami",Miami,Hard Rock Stadium,Round of 32,South Korea,England,17,4,...,0,0,0.62,2.53,73019,Referee_15,Sunny,1,4,England
95,M096,2026-09-14,"MetLife Stadium, New York",New York,MetLife Stadium,Round of 16,Nigeria,Australia,19,21,...,0,0,2.20,0.81,83781,Referee_23,Sunny,3,2,Nigeria
102,M103,2026-09-21,"SoFi Stadium, Los Angeles",Los Angeles,SoFi Stadium,Third Place,Australia,Saudi Arabia,21,39,...,0,0,1.04,2.29,56236,Referee_29,Partly Cloudy,3,2,Australia

In [43]:
df['Total_goals'] = df["Team_1_Goals"] + df["Team_2_Goals"]

In [ ]:
df2 = df.groupby("Stage")['Total_goals'].mean()

Stage
Final            1.000000
Group Stage      2.472222
Quarter Final    2.750000
Round of 16      2.625000
Round of 32      2.812500
Semi Final       3.000000
Third Place      5.000000
Name: Total_goals, dtype: float64

In [46]:
df2 = df.groupby('Referee').size()
df2.sort_values(ascending=False)

Referee
Referee_29    6
Referee_3     6
Referee_7     6
Referee_39    6
Referee_31    4
Referee_35    4
Referee_5     4
Referee_16    4
Referee_15    4
Referee_8     3
Referee_28    3
Referee_1     3
Referee_4     3
Referee_36    3
Referee_19    3
Referee_25    3
Referee_2     3
Referee_30    2
Referee_12    2
Referee_37    2
Referee_27    2
Referee_14    2
Referee_40    2
Referee_38    2
Referee_32    2
Referee_23    2
Referee_18    2
Referee_22    2
Referee_24    2
Referee_26    2
Referee_9     2
Referee_34    2
Referee_10    1
Referee_11    1
Referee_13    1
Referee_21    1
Referee_20    1
Referee_33    1
dtype: int64

In [47]:
df

,Match_ID,Date,Venue,City,Stadium,Stage,Team_1,Team_2,Team_1_FIFA_Rank,Team_2_FIFA_Rank,...,Team_2_Red_Cards,Team_1_xG,Team_2_xG,Attendance,Referee,Weather,Team_1_Goals,Team_2_Goals,Winner,Total_goals
0,M001,2026-06-11,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Group Stage,Qatar,Italy,41,8,...,0,1.24,1.14,67651,Referee_3,Sunny,3,2,Qatar,5
1,M002,2026-06-12,"MetLife Stadium, New York",New York,MetLife Stadium,Group Stage,Portugal,USA,6,14,...,0,1.57,0.10,50463,Referee_28,Rainy,0,0,Draw,0
2,M003,2026-06-13,"Mercedes-Benz Stadium, Atlanta",Atlanta,Mercedes-Benz Stadium,Group Stage,Morocco,Belgium,18,10,...,0,2.43,1.14,70108,Referee_35,Sunny,2,0,Morocco,2
3,M004,2026-06-14,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Group Stage,Ecuador,Portugal,25,6,...,0,0.98,1.10,45229,Referee_15,Sunny,0,3,Portugal,3
4,M005,2026-06-15,"Mercedes-Benz Stadium, Atlanta",Atlanta,Mercedes-Benz Stadium,Group Stage,Ecuador,Morocco,25,18,...,0,1.55,0.10,44679,Referee_39,Cloudy,0,0,Draw,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,M100,2026-09-18,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Quarter Final,Japan,Germany,16,7,...,0,1.37,1.78,77976,Referee_29,Rainy,1,2,Germany,3
100,M101,2026-09-19,"Lumen Field, Seattle",Seattle,Lumen Field,Semi Final,Qatar,Australia,41,21,...,0,1.10,1.08,60342,Referee_30,Partly Cloudy,2,1,Qatar,3
101,M102,2026-09-20,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Semi Final,France,England,3,4,...,0,2.41,1.44,42688,Referee_29,Cloudy,3,0,France,3
102,M103,2026-09-21,"SoFi Stadium, Los Angeles",Los Angeles,SoFi Stadium,Third Place,Australia,Saudi Arabia,21,39,...,0,1.04,2.29,56236,Referee_29,Partly Cloudy,3,2,Australia,5
103,M104,2026-09-22,"Mercedes-Benz Stadium, Atlanta",Atlanta,Mercedes-Benz Stadium,Final,Cameroon,Iran,34,40,...,0,1.11,1.10,82421,Referee_22,Sunny,1,0,Cameroon,1

In [49]:
df3 =df.groupby("Stadium")["Attendance"].mean().sort_values(ascending=False)

In [50]:
df3

Stadium
Mercedes-Benz Stadium    66661.058824
MetLife Stadium          65456.533333
Estadio Azteca           63428.937500
BC Place                 62335.083333
Hard Rock Stadium        61530.777778
Lumen Field              61311.700000
SoFi Stadium             59309.071429
AT&T Stadium             59097.090909
Name: Attendance, dtype: float64

In [54]:
df[df['Winner'] != 'Draw'].groupby('Winner').size().sort_values(ascending = False)

Winner
Poland          5
England         4
Morocco         4
Japan           4
South Korea     4
Australia       3
Portugal        3
Netherlands     3
Germany         3
France          3
Canada          3
Tunisia         2
Sweden          2
Cameroon        2
Venezuela       2
Peru            2
South Africa    2
Qatar           2
Nigeria         2
Senegal         2
Jamaica         2
Colombia        2
Chile           1
Belgium         1
Algeria         1
Italy           1
Ecuador         1
Croatia         1
Costa Rica      1
Egypt           1
Mexico          1
Ghana           1
Iran            1
Paraguay        1
Panama          1
New Zealand     1
Saudi Arabia    1
Turkey          1
dtype: int64

In [58]:
df.groupby("Stage")["Attendance"].agg(['mean','max'])

                       mean    max
Stage
Final          82421.000000  82421
Group Stage    60453.902778  83790
Quarter Final  71709.250000  78592
Round of 16    65882.375000  83781
Round of 32    69812.187500  84944
Semi Final     51515.000000  60342
Third Place    56236.000000  56236

In [63]:
df['Goal_Diff'] = df['Team_1_Goals'] - df['Team_2_Goals']
df['Total_Shots'] = df['Team_1_Shots'] + df['Team_2_Shots']
df['Rank_Diff'] = df['Team_1_FIFA_Rank'] - df['Team_2_FIFA_Rank']
df['Possession_Diff'] = df['Team_1_Possession'] - df['Team_2_Possession']

In [ ]:
def get_result(row):
    if row['Winner'] == row['Team_1']:
        return 1
    elif row['Winner'] == row['Team_2']:
        return 2
    else:
        return 0

df['Result'] = df.apply(get_result, axis=1)

,Match_ID,Date,Venue,City,Stadium,Stage,Team_1,Team_2,Team_1_FIFA_Rank,Team_2_FIFA_Rank,...,Weather,Team_1_Goals,Team_2_Goals,Winner,Total_goals,Goal_Diff,Total_Shots,Total_Shots,Rank_Diff,Possession_Diff
0,M001,2026-06-11,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Group Stage,Qatar,Italy,41,8,...,Sunny,3,2,Qatar,5,1,23,23,33,-30
1,M002,2026-06-12,"MetLife Stadium, New York",New York,MetLife Stadium,Group Stage,Portugal,USA,6,14,...,Rainy,0,0,Draw,0,0,23,23,-8,-16
2,M003,2026-06-13,"Mercedes-Benz Stadium, Atlanta",Atlanta,Mercedes-Benz Stadium,Group Stage,Morocco,Belgium,18,10,...,Sunny,2,0,Morocco,2,2,19,19,8,-18
3,M004,2026-06-14,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Group Stage,Ecuador,Portugal,25,6,...,Sunny,0,3,Portugal,3,-3,20,20,19,4
4,M005,2026-06-15,"Mercedes-Benz Stadium, Atlanta",Atlanta,Mercedes-Benz Stadium,Group Stage,Ecuador,Morocco,25,18,...,Cloudy,0,0,Draw,0,0,17,17,7,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,M100,2026-09-18,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Quarter Final,Japan,Germany,16,7,...,Rainy,1,2,Germany,3,-1,18,18,9,-22
100,M101,2026-09-19,"Lumen Field, Seattle",Seattle,Lumen Field,Semi Final,Qatar,Australia,41,21,...,Partly Cloudy,2,1,Qatar,3,1,23,23,20,-22
101,M102,2026-09-20,"Estadio Azteca, Mexico City",Mexico City,Estadio Azteca,Semi Final,France,England,3,4,...,Cloudy,3,0,France,3,3,24,24,-1,-8
102,M103,2026-09-21,"SoFi Stadium, Los Angeles",Los Angeles,SoFi Stadium,Third Place,Australia,Saudi Arabia,21,39,...,Partly Cloudy,3,2,Australia,5,1,27,27,-18,0
103,M104,2026-09-22,"Mercedes-Benz Stadium, Atlanta",Atlanta,Mercedes-Benz Stadium,Final,Cameroon,Iran,34,40,...,Sunny,1,0,Cameroon,1,1,26,26,-6,-20